### ISSUE TITLE
Hafslund Nett Apps popup in Shell component should link to environment specific applications

### ISSUE THREAD

**Issue by kkho** [hafslundnett/hal-components#69]
All the applications are routing to production. If we developers or users use test environment, then the apps should be test.

**Comment by Martinesp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor-Appshell](https://trello.com/c/EXstcJmN/238-refactor-appshell)

**Comment by JGH153** [comment]
Fixed
